### PR TITLE
Added Images

### PR DESCRIPTION
**Pull request by AnjumanHasan**
Added relevant images for visualization of array and linked list

### CODE REVIEW

**Comment by shhossain** [comment]
@AnjumanHasan are you participating in hacktoberfest?

**Comment by AnjumanHasan** [comment]
Yes

**Comment by shhossain** [comment]
@AnjumanHasan if you want to get labeled as "hacktoberfest-accepted" you must submit +300 lines. So if you want to add more to this repo add it and make it +300 or if you don't want to add more currently than I am merging this repo.

**Comment by AnjumanHasan** [comment]
Okay I'll be adding more

**Comment by shhossain** [comment]
Oka than I am putting this PR on hold.

**Comment by shhossain** [comment]
@AnjumanHasan is your adding completed?

**Review by shhossain — APPROVED** [review]

**Review by shhossain — APPROVED** [review]

**Pull request merged**
