### PR TITLE
add hashing approach to search an item

### LINKED ISSUE #135: Add hashing approach to search an item
I would like to Add hashing approach to search an item

### PR DESCRIPTION
**Pull request by khareyash05**
Closes #135

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
Need to add hashing reference in algo/searching/readme.md with short description.

**Comment by khareyash05** [comment]
> Need to add hashing reference in algo/searching/readme.md with short description.

So I need to mention code for hashing right??

**Review by shhossain — APPROVED** [review]

**Comment by khareyash05** [comment]
@shhossain Could you please add the hacktoberfest label to the same

**Comment by shhossain** [comment]
@khareyash05 needed 100+ unique additions to get "hacktoberfest" label.

**Pull request merged**
