### PR TITLE
Include Traveling Salesman Problem documentation

### PR DESCRIPTION
**Pull request by SamuelBFavarin**
## Proposed changes

Include the Traveling Salesman Problem documentation.

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Proofreading (fix spelling, grammar, punctuation, accuracy) [More about Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New Files/Folder (adding folder without removing existing one)
- [x] Add/Remove Files (adding/removing existing files/folder)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._

- [x] Tested any code against its gcc/clang or the official binaries and it passes locally with my changes
- [x] I have added the necessary explanation
- [x] I have added the necessary links in the working section
- [x] Added external links

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### Reviewers: 

This will be filled by the people who review this particular Pull Request.

### CODE REVIEW

**Comment by SamuelBFavarin** [comment]
I'm joining Hacktoberfest I would like your approval for this documentation. Thank you!

**Review by shhossain — CHANGES_REQUESTED** [review]
You need to add code for this problem. See other sections for reference.

**Review by shhossain — APPROVED** [review]

**Comment by shhossain** [comment]
@all-contributers add @SamuelBFavarin for doc,code

**Comment by shhossain** [comment]
@all-contributors add @SamuelBFavarin for doc, code.

**Pull request merged**
