### PR TITLE
Added functional programing 

### PR DESCRIPTION
**Pull request by Sarthak950**
Detailed explanation of what functional programming is and every aspect of FP

### CODE REVIEW

**Comment by Sarthak950** [comment]
@shhossain Check this out sir

**Review by shhossain — CHANGES_REQUESTED** [review]
This content will be located within the Programming Languages section, specifically under the Programming Paradigms subsection. You have the option to create a new folder within the Programming Languages section and include a link to Functional Languages within it.

**Comment by Sarthak950** [comment]
@shhossain i thought it will sit aside the object-oriented programming as it is an hype, and we are forgetting about the functional programming but i did move it anyways as u said soo

**Comment by shhossain** [comment]
> @shhossain i thought it will sit aside the object-oriented programming as it is an hype, and we are forgetting about the functional programming but i did move it anyways as u said soo

It is worth noting that in order to add a new section on Functional Programming, we would need to provide significant information and create appropriate subsections. This is why I proposed including it under the Programming Paradigms section. Do you want to include more details and add it to the primary readme?

**Comment by Sarthak950** [comment]
@shhossain i have moved it to the programing section but give me time i will improve the primary readme and will inform you

**Comment by Sarthak950** [comment]
@shhossain

**Review by shhossain — APPROVED** [review]

**Pull request merged**
