### PR TITLE
Added types of queue

### PR DESCRIPTION
**Pull request by pritika163**
Added the types of Queue (Circular Queue and Double Ended Queue)

### CODE REVIEW

**Review by Sabine91 — CHANGES_REQUESTED** [review]
Please format the heading and sub heading properly, otherwise the explaination is good.

**Review by Sabine91 — APPROVED** [review]

**Review by shhossain — APPROVED** [review]

**Review by Sabine91 — APPROVED** [review]

**Comment by pritika163** [comment]
@shhossain I submitted this pr under Hacktoberfest 2022 but it does not have a Hacktoberfest accepted label. Please look into it.

**Comment by shhossain** [comment]
To get accepted label you must submit +100 unique additions. @pritika163

**Comment by pritika163** [comment]
@shhossain So inorder to get the label do I need to add 100 more lines or 30 more lines in another pr will do?

**Comment by shhossain** [comment]
Mainly +100 additions in another PR. @pritika163

**Pull request merged**
