### PR TITLE
Add digital circuits section

### PR DESCRIPTION
**Pull request by namberino**
Section includes: basic logic gates, arithmetic circuits, switching circuits, memory circuits

I added the digital circuit section, this section currently includes some basic circuits, later on this section could be expanded to include more complex circuits like ALU or Program counter. Maybe we could expand this to include how to build a simple CPU computer using digital circuits

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
You need to add digital circuits reference in main readme.

**Comment by namberino** [comment]
@shhossain I updated the readme with a reference to digital circuit

**Review by shhossain — CHANGES_REQUESTED** [review]
I was talking about this readme [https://github.com/shhossain/computer_science/blob/main/README.md](https://github.com/shhossain/computer_science/blob/main/README.md)

**Comment by namberino** [comment]
I've added it in this [commit](https://github.com/shhossain/computer_science/pull/751/commits/19bb3c40d7c3b21b9283c0a3b64909e5b26e1f87)

**Review by shhossain — APPROVED** [review]
Thank you so much for your valuable contribution! Looking forward to more great work from you!

**Comment by shhossain** [comment]
@all-contributors add @namberino for docs

**Pull request merged**
