### PR TITLE
added new readme in Nepali

### PR DESCRIPTION
**Pull request by nelsonuprety1**
With this PR, I have added new translated readme which is in Nepali Language.  And i have also fixed the typo which was in the main file. Thank you

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
Link your readme to main readme.

**Comment by nelsonuprety1** [comment]
> Link your readme to main readme.

@shhossain I have linked the readme to the main readme. Please take a look and let me know. Thank you

**Comment by nelsonuprety1** [comment]
@shhossain hi, may i please know why are the checks failing, do i need to update the files again? Thanks

**Review by shhossain — APPROVED** [review]
@nelsonuprety1 that's not problem.

**Comment by shhossain** [comment]
@all-contributors add @nelsonuprety1 for content

**Pull request merged**
