### PR TITLE
Add linear and non linear classification in datastructures directory.

### PR DESCRIPTION
**Pull request by Nijin-P-S**
Found out that the classification of data structures, whether it is linear or non linear was missing in DataStructures folder. So have added both the classification files.
If any changes required let me know.

Thanks,
Nijin

### CODE REVIEW

**Review by Sabine91 — APPROVED** [review]
Great work

**Comment by Nijin-P-S** [comment]
Hi @Sabine91 , is it possible for you to add "hacktoberfest" and  "hacktoberfest-accepted" tags?

**Comment by Sabine91** [comment]
yea i will, just one thing i forgot to do before merging i will revert and merge it again. dont worry i will add the tag

**Comment by Sabine91** [comment]
nvm i will do my own commit

**Comment by Sabine91** [comment]
the maintainer(@shhossain ) might review the tags and see if the PR is up to the quality

**Comment by Nijin-P-S** [comment]
Sure @Sabine91 . Thanks by the way.

**Comment by shhossain** [comment]
@Nijin-P-S Plseas add +100 additions. And it must be unique. To get accepted label.

**Pull request merged**
