### PR TITLE
Special Purpose Register and Types

### PR DESCRIPTION
**Pull request by shaanrxx**
## Proposed changes

The recent commit I made includes several updates. Firstly, there were corrections made to typing errors. I also added a new section, giving a brief overview about special-purpose registers found in CPUs. I also added an explanation of cache and discussed cache coherency. These changes are important as they allow Sfor more detail of the components of CPU architecture and how they operate. Due to their being so many registers, I felt it was important to start adding some of the functions of certain registers in as currently there is a short overview of the need for registers. Additionally, there are several reasons for the purpose of Cache and I wanted to add a few more reasons.

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [x ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x ] New content (new section, new readme, etc.)
- [x ] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ ] Tested any code that was added/modified in this PR
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ ] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @shaanrxx for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

### CODE REVIEW

**Review by shhossain — APPROVED** [review]
No problem. Merging.

**Comment by shhossain** [comment]
@all-contributors add @shaanrxx for content

**Comment by shaanrxx** [comment]
thank you for accepting my changes!

**Comment by shhossain** [comment]
@shaanrxx You're welcome! Glad to have your contributions on board.

**Pull request merged**
