### PR TITLE
Added a section about the CPU

### PR DESCRIPTION
**Pull request by umadhatri**
I added some additional information about the CPU

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
Create a folder called "CPU". Inside the folder create a readme and add this info there.
```
## Memory or Storage Unit:
The memory or storage unit stores vital information such as instructions, data, and intermediate results. The memory unit is responsible for transferring information to other units of the computer when needed. It is also known as an internal storage unit or the main memory or the primary storage or Random Access Memory (RAM) as all these are storage devices.

## Control Unit:
The control unit controls the operations of all parts of the computer but does not carry out any actual data processing operations. Its functions include:
a) controlling the transfer of data and instructions among other units of a computer.
b) managing and coordinating all the units of the computer.
c) obtaining the instructions from the memory, interpreting them, and directing the operations of the computer.
d) responsible for communication with peripheral devices such as input and output devices.

## Arithmetic and Logic Unit (ALU)
The ALU, as can be seen, is made of two sections. They are:
1) The Arithmetic Unit: It is responsible for the arithmetic operations such as addition, subtraction, multiplication, and division. Any complicated actions are done by repeating the same steps over and over to achieve the final result
2) The Logic Unit: As the name gives it away, it performs all the logical operations such as selecting, comparing, matching, and merging data
```

and change the link to that. If you have any questions ask me bellow. You can also see examples of this in other sections.

**Comment by umadhatri** [comment]
Will work on that immediately

**Comment by umadhatri** [comment]
Where do I add the CPU file?

**Review by shhossain — CHANGES_REQUESTED** [review]
change "partsOfACPU.md" to readme.md

And some work needs to be done which I will fix after merging.

**Comment by shhossain** [comment]
Merging. But some work needs to be done. You can see the next commit to see fixes.

**Comment by umadhatri** [comment]
Sure

**Comment by shhossain** [comment]
@umadhatri you can see the changes.

**Pull request merged**
