### PR TITLE
Contri

### PR DESCRIPTION
**Pull request by shhossain**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. Your PR title can be also used in here.

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ ] New content (new section, new readme, etc)
- [ ] Modifications (modifying existing content, adding new content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ ] Tested any code that was added/modified in this PR
- [ ] Added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ ] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### Reviewers: 
- [ ] @username

_If you adding code, please make sure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information to the code._

### CODE REVIEW

**Comment by shhossain** [comment]
@all-contributors please add @shhossain

**Comment by shhossain** [comment]
@all-contributors
please add @shhossain for content.
please add @imams12 for content.
please add @Sabine91 for content.
please add @ishan-im for content.
please add @Rajesh144142 for content.
please add @Apoorva08102000 for content.
please add @apoorva1823000 for content.
please add @utopian-coder for content.
please add @ShuvamBag for content.
please add @rahulmangla28 for content.
please add @altafshaikh for content.
please add @rajdeepdas2000 for content.
please add @kanaujiyaaditi for content.
please add @its-red-eagle for content.
please add @alwenpy for content.
please add @Naprila for content.
please add @KimtVak8143 for content.
please add @DryHitman for content.
please add @harshkulkarni17 for content.
please add @subrata-9999 for content.
please add @manas6699 for content.
please add @ATREAY for content.
please add @Talib-Hossain for content.
please add @SreeHaran for content.
please add @kusumita29 for content.
please add @geeky-auro for content.
please add @Aiyan-Faras for content.
please add @PriyanshiDavid for content.
please add @ishancode-dev for content.
please add @NikhilShrivastava for content.
please add @deepshikha2708 for content.
please add @rishiwardhan for content.
please add @DevTMK for content.
please add @JaiMehrotra02 for content.
please add @AbhijitTurate for content.
please add @NishantWankhade for content.
please add @pritika163 for content.
please add @AnjumanHasan for content.
please add @Asthavarshneyy for content.
please add @Gcettbdeveloper for content.
please add @Elstuhn for content.
please add @ShivanshDengla for content.
please add @Tetricz for content.
please add @Jayesh2812 for content.
please add @ayushverma14 for content.
please add @pratikkumar399 for content.
please add @yash-ch for content.
please add @pranavyatnalkar for content.
please add @jeremiaaxel for content.
please add @akhil-maker for content.
please add @DevZahraShahid for content.
please add @Mihir20K for content.
please add @Code-N-Bug for content.
please add @computerwala for content.
please add @mauriallegrettiswnat for content.
please add @Bruno-Vasconcellos-Betella for content.
please add @febiarifin for content.
please add @umadhatri for content.
please add @dinesh9-ai for content.
please add @Dheerajsoni93 for content.
please add @Sahilrao09 for content.
please add @OjashKush for content.
please add @Sleep-lover for content.
please add @Wahaj-Raza for content.
please add @WahajRaza1 for content.
please add @RavenColEvol for content.
please add @UperscuzziSchoolAcc for content.
please add @AdarshBajpai67 for content.
please add @Deepak-Kharah for content.
please add @sairohit360 for content.
please add @sairohitzl for content.
please add @RavalJinit for content.
please add @Vovka1759 for content.
please add @Nijin-P-S for content.
please add @avinilcode for content.
please add @FercueNat for content.
please add @khareyash05 for content.
please add @ayushanand16 for content.
please add @DharmaWarrior for content.
please add @hitarthraval for content.
please add @WiemBorchani for content.
please add @Kambo2320 for content.
please add @denschiro for content.
please add @nishat48 for content.
please add @mdfaizanahmed786 for content.
please add @manish831 for content.
please add @lokesh-katari for content.
please add @ZahraShahid for content.
please add @glenntu15 for content.
please add @vinayak9303 for content.
please add @Satyajeetbh for content.
please add @P-Dhruva-Teja for content.
please add @helloausrine for content.
please add @SourabhJoshi209 for content.
please add @codewithfan for content.
please add @anmspro for content.
please add @skyrunner360 for content.
please add @Atharv-Nalwade for content.
please add @Retr0Sushi for content.

**Comment by shhossain** [comment]
@all-contributors
 please add @Apoorva08102000 for content.

**Comment by shhossain** [comment]
add @apoorva1823000 for content. @all-contributors

**Comment by shhossain** [comment]
@all-contributors add @apoorva1823000  for content

**Comment by shhossain** [comment]
@all-contributors
add @utopian-coder for content, code, doc.
please add @ShuvamBag for content, doc, code.
please add @rahulmangla28 for content, doc, code.

**Comment by shhossain** [comment]
commnet from git cli

**Comment by shhossain** [comment]
@all-contributors add @shhossain for doc.

**Comment by shhossain** [comment]
@all-contributors add @imams12 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Sabine91 for doc.

**Comment by Elstuhn** [comment]
I'm still not added in the contributors section

**Comment by Elstuhn** [comment]
Alright, thank you!

> @Elstuhn as the contribution section is large. It is taking time to add all of them. Hopefully, I will add it by today.

**Comment by shhossain** [comment]
@all-contributors add @ishan-im for doc.

**Comment by shhossain** [comment]
@all-contributors add @Rajesh144142 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Apoorva08102000 for doc.

**Comment by shhossain** [comment]
@all-contributors add @apoorva1823000 for doc.

**Comment by shhossain** [comment]
@all-contributors add @utopian-coder for doc.

**Comment by shhossain** [comment]
@all-contributors add @ShuvamBag for doc.

**Comment by shhossain** [comment]
@all-contributors add @rahulmangla28 for doc.

**Comment by shhossain** [comment]
@all-contributors add @altafshaikh for doc.

**Comment by shhossain** [comment]
@all-contributors add @rajdeepdas2000 for doc.

**Comment by shhossain** [comment]
@all-contributors add @kanaujiyaaditi for doc.

**Comment by shhossain** [comment]
@all-contributors add @its-red-eagle for doc.

**Comment by shhossain** [comment]
@all-contributors add @alwenpy for doc.

**Comment by shhossain** [comment]
@all-contributors add @Naprila for doc.

**Comment by shhossain** [comment]
@all-contributors add @KimtVak8143 for doc.

**Comment by shhossain** [comment]
@all-contributors add @DryHitman for doc.

**Comment by shhossain** [comment]
@all-contributors add @harshkulkarni17 for doc.

**Comment by shhossain** [comment]
@all-contributors add @subrata-9999 for doc.

**Comment by shhossain** [comment]
@all-contributors add @manas6699 for doc.

**Comment by shhossain** [comment]
@all-contributors add @ATREAY for doc.

**Comment by shhossain** [comment]
@all-contributors add @Talib-Hossain for doc.

**Comment by shhossain** [comment]
@all-contributors add @SreeHaran for doc.

**Comment by shhossain** [comment]
@all-contributors add @kusumita29 for doc.

**Comment by shhossain** [comment]
@all-contributors add @geeky-auro for doc.

**Comment by shhossain** [comment]
@all-contributors add @Aiyan-Faras for doc.

**Comment by shhossain** [comment]
@all-contributors add @PriyanshiDavid for doc.

**Comment by shhossain** [comment]
@all-contributors add @ishancode-dev for doc.

**Comment by shhossain** [comment]
@all-contributors add @NikhilShrivastava for doc.

**Comment by shhossain** [comment]
@all-contributors add @rishiwardhan for doc.

**Comment by shhossain** [comment]
@all-contributors add @DevTMK for doc.

**Comment by shhossain** [comment]
@all-contributors add @AbhijitTurate for doc.

**Comment by shhossain** [comment]
@all-contributors add @NishantWankhade for doc.

**Comment by shhossain** [comment]
@all-contributors add @pritika163 for doc.

**Comment by shhossain** [comment]
@all-contributors add @AnjumanHasan for doc.

**Comment by shhossain** [comment]
@all-contributors add @Asthavarshneyy for doc.

**Comment by shhossain** [comment]
@all-contributors add @Gcettbdeveloper for doc.

**Comment by shhossain** [comment]
@all-contributors add @Elstuhn for doc.

**Comment by shhossain** [comment]
@all-contributors add @ShivanshDengla for doc.

**Comment by shhossain** [comment]
@all-contributors add @Tetricz for doc.

**Comment by shhossain** [comment]
@all-contributors add @Jayesh2812 for doc.

**Comment by shhossain** [comment]
@all-contributors add @ayushverma14 for doc.

**Comment by shhossain** [comment]
@all-contributors add @pratikkumar399 for doc.

**Comment by shhossain** [comment]
@all-contributors add @yash-ch for doc.

**Comment by shhossain** [comment]
@all-contributors add @pranavyatnalkar for doc.

**Comment by shhossain** [comment]
@all-contributors add @jeremiaaxel for doc.

**Comment by shhossain** [comment]
@all-contributors add @akhil-maker for doc.

**Comment by shhossain** [comment]
@all-contributors add @DevZahraShahid for doc.

**Comment by shhossain** [comment]
@all-contributors add @Mihir20K for doc.

**Comment by shhossain** [comment]
@all-contributors add @Code-N-Bug for doc.

**Comment by shhossain** [comment]
@all-contributors add @computerwala for doc.

**Comment by shhossain** [comment]
@all-contributors add @mauriallegrettiswnat for doc.

**Comment by shhossain** [comment]
@all-contributors add @Bruno-Vasconcellos-Betella for doc.

**Comment by shhossain** [comment]
@all-contributors add @febiarifin for doc.

**Comment by shhossain** [comment]
@all-contributors add @umadhatri for doc.

**Comment by shhossain** [comment]
@all-contributors add @dinesh9-ai for doc.

**Comment by shhossain** [comment]
@all-contributors add @Dheerajsoni93 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Sahilrao09 for doc.

**Comment by shhossain** [comment]
@all-contributors add @OjashKush for doc.

**Comment by shhossain** [comment]
@all-contributors add @Wahaj-Raza for doc.

**Comment by shhossain** [comment]
@all-contributors add @WahajRaza1 for doc.

**Comment by shhossain** [comment]
@all-contributors add @RavenColEvol for doc.

**Comment by shhossain** [comment]
@all-contributors add @UperscuzziSchoolAcc for doc.

**Comment by shhossain** [comment]
@all-contributors add @AdarshBajpai67 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Deepak-Kharah for doc.

**Comment by shhossain** [comment]
@all-contributors add @sairohitzl for doc.

**Comment by shhossain** [comment]
@all-contributors add @RavalJinit for doc.

**Comment by shhossain** [comment]
@all-contributors add @Vovka1759 for doc.

**Comment by shhossain** [comment]
@all-contributors add @avinilcode for doc.

**Comment by shhossain** [comment]
@all-contributors add @FercueNat for doc.

**Comment by shhossain** [comment]
@all-contributors add @khareyash05 for doc.

**Comment by shhossain** [comment]
@all-contributors add @ayushanand16 for doc.

**Comment by shhossain** [comment]
@all-contributors add @DharmaWarrior for doc.

**Comment by shhossain** [comment]
@all-contributors add @hitarthraval for doc.

**Comment by shhossain** [comment]
@all-contributors add @WiemBorchani for doc.

**Comment by shhossain** [comment]
@all-contributors add @Kambo2320 for doc.

**Comment by shhossain** [comment]
@all-contributors add @denschiro for doc.

**Comment by shhossain** [comment]
@all-contributors add @mdfaizanahmed786 for doc.

**Comment by shhossain** [comment]
@all-contributors add @manish831 for doc.

**Comment by shhossain** [comment]
@all-contributors add @lokesh-katari for doc.

**Comment by shhossain** [comment]
@all-contributors add @ZahraShahid for doc.

**Comment by shhossain** [comment]
@all-contributors add @glenntu15 for doc.

**Comment by shhossain** [comment]
@all-contributors add @vinayak9303 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Satyajeetbh for doc.

**Comment by shhossain** [comment]
@all-contributors add @P-Dhruva-Teja for doc.

**Comment by shhossain** [comment]
@all-contributors add @helloausrine for doc.

**Comment by shhossain** [comment]
@all-contributors add @SourabhJoshi209 for doc.

**Comment by shhossain** [comment]
@all-contributors add @codewithfan for doc.

**Comment by shhossain** [comment]
@all-contributors add @anmspro for doc.

**Comment by shhossain** [comment]
@all-contributors add @skyrunner360 for doc.

**Comment by shhossain** [comment]
@all-contributors add @Atharv-Nalwade for doc.

**Comment by shhossain** [comment]
@all-contributors add @Retr0Sushi for doc.

**Comment by shhossain** [comment]
@all-contributors add @Talib-Hossain for doc.

**Comment by shhossain** [comment]
@all-contributors add @umadhatri for doc.

**Comment by shhossain** [comment]
@all-contributors add @sahooabhipsa10 for doc.

**Comment by shhossain** [comment]
@all-contributors add @apoorva1823000 for doc.

**Comment by shhossain** [comment]
@all-contributors add @shhossain for doc

**Comment by shhossain** [comment]
@all-contributors add @sahooabhipsa10 for doc

**Comment by shhossain** [comment]
@all-contributors add @Subrata-Pramanik for doc

**Comment by shhossain** [comment]
@all-contributors add @SamuelBFavarin for doc

**Comment by shhossain** [comment]
@all-contributors add @SohamDey80 for doc

**Comment by shhossain** [comment]
@all-contributors add @kusumita29 for doc

**Comment by shhossain** [comment]
@all-contributors add @Yash1107 for doc

**Pull request merged**
