### PR TITLE
added SwapSort

### PR DESCRIPTION
**Pull request by Naprila**
Implementations of C++ and C has also been added

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
Add a link to swapsort in [Sorting](https://github.com/shhossain/computer_science/blob/main/Algorithms/Sorting/readme.md).

**Review by shhossain — APPROVED** [review]
Merging.

**Comment by Naprila** [comment]
Thanks. 
Will add Count Sort as well soon.

**Comment by shhossain** [comment]
@Naprila oka.

**Pull request merged**
