### PR TITLE
Aiyan

### PR DESCRIPTION
**Pull request by Aiyan-Faras**
made some changes

### CODE REVIEW

**Review by Sabine91 — APPROVED** [review]

**Comment by Sabine91** [comment]
wait a sec, is the code in java coz its looking a lot like c

**Review by shhossain — APPROVED** [review]

**Comment by shhossain** [comment]
@Aiyan-Faras fork the latest repo.

**Review by Sabine91 — CHANGES_REQUESTED** [review]
please check your code there is a lot of syntax errors

**Comment by Aiyan-Faras** [comment]
@Sabine91 @shhossain  Code is written in java language , Array.length method is available in java.

**Review by shhossain — APPROVED** [review]

**Review by Sabine91 — APPROVED** [review]

**Pull request merged**
