### PR TITLE
added number system conversion for 6 languages C, CPP , JS, TS, Lua, Java

### PR DESCRIPTION
**Pull request by Sarthak950**

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
@Sarthak950, consider enhancing the code by incorporating additional comments to improve code readability and understanding. Additionally, ensure that you include links to these code files in the "Number System/readme.md" file for better documentation and accessibility.

**Comment by Sarthak950** [comment]
@shhossain done adding comments for readability and linked files in the readme.md

**Review by shhossain — APPROVED** [review]
No issues were detected. Proceeding with the merge to the main branch. 🚀

Lastly, I'd like to express my gratitude for your valuable contribution, which involved implementing number system conversions for six different languages. Thank you! 👏👍

**Comment by shhossain** [comment]
@all-contributors add @Sarthak950 for code.

**Comment by Sarthak950** [comment]
@shhossain Thank you very much Sir 🎶

**Pull request merged**
