### PR TITLE
String based Algorithms added

### PR DESCRIPTION
**Pull request by architO21**
## Proposed changes

I have added a new directory known as String based algorithms and added string matching codes inside of it

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ x] New content (new section, new readme, etc.)
- [ x] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ x] Tested any code that was added/modified in this PR
- [x] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ ] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
Please ensure that your code is thoroughly documented with meaningful comments and includes comprehensive explanations in the algorithms section of the README file.

**Comment by architO21** [comment]
> Please ensure that your code is thoroughly documented with meaningful comments and includes comprehensive explanations in the algorithms section of the README file.

I have applied the changes that you had mentioned in my code and also updated the readme file

**Review by shhossain — CHANGES_REQUESTED** [review]
Change this:
1. Fix the code format [Tutorial](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)
3. Rename the folder from `Stringbasedalgorithms` to `String Based Algorithms`.

Finally, Thank you for your valuable contribution.

**Comment by architO21** [comment]
I have changed the name of the repository and have written code in the format as you had mentioned. Please review my changes

**Review by shhossain — APPROVED** [review]
Nice work.

**Comment by shhossain** [comment]
@all-contributors add @architO21 for code and content.

**Comment by architO21** [comment]
Thankyou @shhossain this was my first contribution in open source, I got to learn a lot working with you

**Comment by shhossain** [comment]
Congratulations on your first open-source contribution! I'm glad you had a great learning experience. Keep it up! @architO21

**Pull request merged**
