### PR TITLE
Updated Registers, Cache and RAM section of the ReadMe

### PR DESCRIPTION
**Pull request by ayushanand16**
Added more info about Registers such as the basic types of registers , their function , and their storage capacity. Also added a new definition of registers that they are a collection of flip flop (which is a device which stores 1 bit of memory).

### CODE REVIEW

**Comment by ayushanand16** [comment]
PR for Issue #1

**Review by shhossain — CHANGES_REQUESTED** [review]
Add  short descriptions in the main readme and long descriptions in 'Registers Cache and RAM\readme.md'
folder.

**Comment by shhossain** [comment]
@ayushanand16 change the requested.

**Comment by ayushanand16** [comment]
> @ayushanand16 change the requested.

Will do. Thanks

**Comment by ayushanand16** [comment]
@shhossain  Made the requested changes.

**Review by shhossain — APPROVED** [review]
Approved. Merging.

**Pull request merged**
