### PR TITLE
create new web scraping section with readme overview and basic web scraping example

### PR DESCRIPTION
**Pull request by jakenybo**
create new web scraping section with readme overview and basic web scraping example

## Proposed changes

Add new Web Scraping section. Create a readme overview of Web Scraping as well as a basic Web Scraping example.

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New content (new section, new readme, etc.)
- [ ] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [x] Tested any code that was added/modified in this PR
- [x] Added external links
- [ ] Added internal links
- [x] Added images
- [ ] Added videos
- [x] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

### CODE REVIEW

**Comment by jakenybo** [comment]
https://github.com/all-contributors please add @jakenybo for content

**Review by shhossain — CHANGES_REQUESTED** [review]
can you change `Web Technology/Web Scraping/Examples/0_Basic_Web_Scraping_Example.ipynb` to a markdown file?

**Comment by jakenybo** [comment]
yes, i could, but then you would lose the functionality of being able to run snippets of Python code within the jupyter notebook.  this is a very powerful way to understand the code. Jupyter Notebooks are becoming very popular in educational mediums. i'm currently taking master's courses that use jupyter notebooks like this for education.

i would strongly recommend that we make a change to allow jupyter notebooks to be used for teaching in this project. i feel that they would greatly add to the educational interactivity of this project. but, you are the project owner and i respect your vision for the project. do you want me to change my learning material for this new web scraping to markdown `.md` files or will you allow us to implement jupyter notebooks for teaching?

i'll follow whatever you decide, thanks

**Comment by shhossain** [comment]
@jakenybo okay. let it stay.

**Review by shhossain — APPROVED** [review]

**Comment by shhossain** [comment]
@all-contributors please add @jakenybo for content and code

**Pull request merged**
