### PR TITLE
Add swapSort's Python code

### PR DESCRIPTION
**Pull request by snowflake1201**
## Proposed changes

Add SwapSort's Python code

## Types of changes

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ ] New content (new section, new readme, etc)
- [x] Modifications (modifying existing content, adding new content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [x] Tested any code that was added/modified in this PR
- [ ] Added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [x] Added code snippets

## Further comments

None.

## Adding your name to the contributor's list

Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_If you add code, please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information to the code._

### CODE REVIEW

**Comment by snowflake1201** [comment]
Hello everyone,
This is my first contribution.
Please let me know if I'm doing something wrong.
hope I can help.

**Review by shhossain — APPROVED** [review]
No problem in pull request. Merging.

**Comment by shhossain** [comment]
@all-contributors add @snowflake1201 for code.

**Comment by shhossain** [comment]
> Hello everyone,
> 
> This is my first contribution.
> 
> Please let me know if I'm doing something wrong.
> 
> hope I can help.

Congratulations on you first contribution. @snowflake1201

**Pull request merged**
