### PR TITLE
Updated the Boolean logic readme.md

### PR DESCRIPTION
**Pull request by ayushverma14**
Added the boolean expression,their types and steps of reduction using K-Map.

### CODE REVIEW

**Review by shhossain — APPROVED** [review]
Adding

**Comment by ayushverma14** [comment]
Sir how to get the hackoctober-accepted label ? Do i need to do add more changes

**Comment by shhossain** [comment]
Normally 200 or 300+ qualify full lines get added as accepted but because you content use unique I am adding this as accepted.

**Comment by ayushverma14** [comment]
Thank u sir .Will take care next time

**Pull request merged**
