### PR TITLE
update(data structures): update queue and stack

### PR DESCRIPTION
**Pull request by jeremiaaxel**
Hi, I just updated the stack and queue, and create each dedicated markdown files. Also changed the links of the data structure's list to its dedicated files.

### CODE REVIEW

**Comment by shhossain** [comment]
Data structure/readme.md should have short description. Check long description should be on the desiccated file. See the data structure folder now. Maybe you had the old version of repo forked.

**Review by shhossain — CHANGES_REQUESTED** [review]
Check Data structure/readme.md

**Comment by jeremiaaxel** [comment]
Is it enough or too short to be descriptive?

**Review by shhossain — APPROVED** [review]
Think it's enough. Merging.

**Pull request merged**
