### PR TITLE
Add De Morgan's Laws to readme.md

### PR DESCRIPTION
**Pull request by pranavyatnalkar**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, link to that issue.

I have added De Morgan's Laws of Boolean algebra to the readme.md file

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [More about Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New Files/Folder (adding folder without removing existing one)
- [ ] Add/Remove Files (adding/removing existing files/folder)
- [x] Made an addition to an existing file

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._

- [x] Tested any code against its gcc/clang or the official binaries and it passes locally with my changes
- [x] I have added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### Reviewers: 

This will be filled by the people who review this particular Pull Request.

### CODE REVIEW

**Comment by shhossain** [comment]
@pranavyatnalkar change the requested.

**Comment by pranavyatnalkar** [comment]
@shhossain I didn't understand exactly what you want me to change, should I change the title of my PR?

**Comment by shhossain** [comment]
@pranavyatnalkar I meant to say move de morgan law into Boolean law dedicated section. Goto Boolean law section and in readme add de morgans law.

**Review by shhossain — APPROVED** [review]

**Comment by pranavyatnalkar** [comment]
@shhossain Thank you so much for merging my PR! 😃 This is my first successful merge request. 🥳 Is it okay if I raise more PRs in the coming days?

**Comment by pranavyatnalkar** [comment]
Hey @shhossain could you please add 'hacktoberfest-accepted' label to this PR as well as my upcoming PRs?

**Comment by shhossain** [comment]
@pranavyatnalkar We need over 100 additions to consider adding that label.

**Pull request merged**
