### PR TITLE
Added the topic : ER Model

### PR DESCRIPTION
**Pull request by vikashpatel24**

### CODE REVIEW

**Comment by Sabine91** [comment]
Please update your PR

**Comment by Sabine91** [comment]
the repository was update since your PR, it wont merge until all the conflicts are resolved, u can do it by updating your forked repository.

**Review by Sabine91 — CHANGES_REQUESTED** [review]
the images arent loading cause u changed the file names

**Comment by Sabine91** [comment]
try to see if you can see the images in the readme if not then try a fix otherwise i will msg you in the morning as its getting late here in india, and i dont have my phone on me.

**Comment by Sabine91** [comment]
both cause it seems you cant view any of the photos that you have added.

**Review by Sabine91 — CHANGES_REQUESTED** [review]
Here is what you should do:

Make sure you the filename of the photos are correct
See if they are visible when previewing them

Possible cause:
i think you havent named a few of your files idk but might be causing some problems.

**Review by Sabine91 — CHANGES_REQUESTED** [review]
U havent update the main readme appropriately, also if u can create a whole topic called database, cause adding just a loose concept of no apparent sub topic is not recommended

**Review by shhossain — CHANGES_REQUESTED** [review]
Create a new section data storage and add all of this there,

**Pull request closed without merging**
