### PR TITLE
Method Overloading in Java

### PR DESCRIPTION
**Pull request by BotSonu**
Please add my file in your repo lebel as hacktoberfest 2022

### CODE REVIEW

**Comment by Sabine91** [comment]
Please add atleast 100+ lines if you want your PR to be accepted for hacktoberfest, u can add more if you want, otherwise i will review and see if i can merge your PR.

**Comment by BotSonu** [comment]
Can I add more files on this topic ( short codes ) on the same topic?

**Review by Sabine91 — CHANGES_REQUESTED** [review]
please check the folder in which you are adding files, it seems your at adding them in the root directory.

**Comment by BotSonu** [comment]
Yes Sir. Sorry for that. I am Correcting

**Review by Sabine91 — CHANGES_REQUESTED** [review]
u can add as much as you want, just a few guidelines,
dont create indicidual files for short codes, if they are explaining or part of a topic just create a readme for that topic or add it to the readme of that topic as code snippets.

**Comment by BotSonu** [comment]
okk sir doing

**Comment by Sabine91** [comment]
hey hey no sir, not so formal i am just a kid, in open source code speaks dont write like you work for me

**Comment by BotSonu** [comment]
okay

**Pull request closed without merging**
