### PR TITLE
Created a new section for Signedness

### PR DESCRIPTION
**Pull request by ZRX-SIGMA**
## Proposed changes

Created a new section for Signedness under DataTypes 
Edited, as some of the datatype sizes were wrong and ambiguous

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [x] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New content (new section, new readme, etc.)
- [x] Modifications (modifying existing content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [x] Tested any code that was added/modified in this PR
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [x] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_Please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information._

### CODE REVIEW

**Comment by ZRX-SIGMA** [comment]
@shhossain Can u please help in this, dont know why it failed the test , when I have mostly added and edited Text, and entered 2 codes.

**Comment by shhossain** [comment]
@ZRX-SIGMA, this is not your concern. The code was committed before creating test.py. I will review your content as soon as possible.

**Comment by ZRX-SIGMA** [comment]
> @ZRX-SIGMA, this is not your concern. The code was committed before creating test.py. I will review your content as soon as possible.

ok thanks

**Comment by ZRX-SIGMA** [comment]
@shhossain   It will be helpful if you could add this in hacktoberfest-accepted ..

**Review by shhossain — APPROVED** [review]

**Comment by shhossain** [comment]
@all-contributors add @ZRX-SIGMA for content

**Pull request merged**
