### PR TITLE
Added some more text and code example to Functional Programming

### PR DESCRIPTION
**Pull request by Francesco601**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. Your PR title can be also used in here.

Added some more text and code examples to section Functional Programming and some other grammar edits.

## Types of changes

What types of changes does your content introduce to this project?
_Put an `x` in the boxes that apply (without "`")_

- [ x] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [x] New content (new section, new readme, etc)
- [ x] Modifications (modifying existing content, adding new content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ x] Tested any code that was added/modified in this PR
- [ x] Added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ x] Added code snippets

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_If you add code, please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information to the code._

### CODE REVIEW

**Comment by Francesco601** [comment]
Oops. I mistakenly typed "cond" instead of "cons" in the small Lisp function. Corrected. Sorry....

**Comment by Francesco601** [comment]
Added another subsection on programming language paradigms with example code....

**Review by shhossain — CHANGES_REQUESTED** [review]
@Francesco601, I kindly request you to implement the following refinements:

1. Move the "Programming Language Paradigms" content to a newly created folder specifically dedicated to programming languages.
2. Revise the main readme.md file to include a concise introduction and summary.
3. Add a brief description in the main readme.md file, summarizing the content that has been moved to the new folder.
4. Incorporate links in the main readme.md file to guide readers to the newly created folder where the relocated content can be found.
5. Remember that the main readme should only consist of short descriptions.

Please feel free to reach out if you require any further assistance!

**Review by shhossain — APPROVED** [review]
Merging

**Pull request merged**
