### PR TITLE
Readme for OOPS and Cloud

### PR DESCRIPTION
**Pull request by deepshikha2708**

### CODE REVIEW

**Review by shhossain — APPROVED** [review]

**Comment by deepshikha2708** [comment]
can you please add the labl for the issues and pr?

**Comment by shhossain** [comment]
To get hacktoberfest-approved you need minimum 100 unique additions. @deepshikha2708

**Comment by deepshikha2708** [comment]
ooh ok didnt know this

**Comment by deepshikha2708** [comment]
can I add here more?

**Comment by shhossain** [comment]
@deepshikha2708 no it's already merged. And closed.

**Pull request merged**
