### PR TITLE
Fixing the randomness

### PR DESCRIPTION
**Pull request by Klarab24**
## Proposed changes
There is just random information about anything, complete and incomplete in no specific order.
I tried to section the headings in a few groups according to what i felt, there is content which feels like was there just for PRs and the author didnt intend to write anything meaningfull.

## Types of changes

What types of changes does your content introduce to this project?
Just some reordering and uniform styling in throught the readme

_Put an `x` in the boxes that apply (without "`")_

- [x] Proofreading (fix spelling, grammar, punctuation, accuracy) [Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [] New content (new section, new readme, etc)
- [x] Modifications (modifying existing content, adding new content)
- [ ] Other (please describe)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This simply reminds us of what we will look for before merging your code._
_Note: If you submit code make sure to test it_

- [ ] Tested any code that was added/modified in this PR
- [x] Added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links
- [ ] Added internal links
- [ ] Added images
- [ ] Added videos
- [ ] Added code snippets

## Further comments

There needs to be a uniform writing style in README since this basically where majority of the data, badly chosen heading level and all that just makes it a hell lot confusing.

## Adding your name to the contributor's list
Comment "@all-contributors please add @your_username for content" to add your name to the contributor's list.
_You can change the "content" with any of [this](https://allcontributors.org/docs/en/emoji-key)_

### Reviewers: 
- [ ] @username

_If you add code, please ensure that you are not adding any sensitive information like API keys, secrets, passwords, tokens, usernames, or other credentials. Refrain from adding your name, email, or other personal information to the code._

### CODE REVIEW

**Comment by Klarab24** [comment]
This commit is not finish yet, there needs to be a lot of discussion before these things merge.

**Comment by Klarab24** [comment]
@shhossain please review

**Comment by shhossain** [comment]
@Klarab24 can you remove the space between list item in table of contents.

**Comment by Klarab24** [comment]
sure, but this is not the final commit so dont merge directly

**Comment by shhossain** [comment]
Okay, let me know when you're finished, @Klarab24.

**Comment by Klarab24** [comment]
@shhossain i really need an answer on weather the order in the contents table is perfect so that i start reordering the content in the readme, also i changed the heading level it now just looks much better to me but comment on that one too, and just see if non of the code from the last commit is missing.

**Comment by shhossain** [comment]
I suggest you put all changes in the main file as it's hard to see the difference in the 'copy' file.

**Pull request closed without merging**
