### PR TITLE
New

### PR DESCRIPTION
**Pull request by kanaujiyaaditi**
## Proposed changes

Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, link to that issue.

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [More about Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ x] New Files/Folder (adding folder without removing existing one)
- [x ] Add/Remove Files (adding/removing existing files/folder)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._

- [x ] Tested any code against its gcc/clang or the official binaries and it passes locally with my changes
- [ x] I have added the necessary explanation
- [ x] I have added the necessary links in the working section
- [ x] Added external links

## Further comments
Provided some more examples of ER diagram and deleted the unwanted files. 

### Reviewers: 

This will be filled by the people who review this particular Pull Request.

### CODE REVIEW

**Comment by shhossain** [comment]
@kanaujiyaaditi what you want to add is not clear enough.

**Comment by kanaujiyaaditi** [comment]
I added some examples of E R model in DBMS folder.

**Comment by shhossain** [comment]
@kanaujiyaaditi add example here "https://github.com/shhossain/computer_science/blob/main/DBMS/ER%20Model/readme.md"

**Comment by Sabine91** [comment]
looks the changes were merged in this PR #355

**Pull request closed without merging**
