### PR TITLE
RSA encryption

### PR DESCRIPTION
**Pull request by NitroNik7**

### CODE REVIEW

**Comment by shhossain** [comment]
@NitroNik7 rsa should go to cryptography section. As we have not created that section you can create Cryptography section and add rsa algorithm there with explanations. See other sections for how to do it.

**Comment by NitroNik7** [comment]
Thank you, I will do the needful.

**Review by shhossain — CHANGES_REQUESTED** [review]
Change requested

**Comment by shhossain** [comment]
@NitroNik7 add this in the newly created cryptography section. Add readme and provide your code there with the explanation.

**Pull request closed without merging**
