### PR TITLE
Added How a system boots up. This is corresponding to the issue 642. …

### PR DESCRIPTION
**Pull request by manavmittal05**
…The file added is "OS_Boot_Process.md" in "Operating Systems" directory.

## Proposed changes

Added the detailed process of how a system boots.

## Types of changes

added a file named OS_Boot_Process.md. Resolved issue #642

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
It must be linked to operating systems/readme.md.

Add a short description in `operation systems/readme.md` and link that to `os_boot_process.md`  (filename change required)

**Comment by manavmittal05** [comment]
I have made the suggested changes.

**Review by shhossain — APPROVED** [review]
Merging.

**Comment by shhossain** [comment]
@all-contributor add @manavmittal05 for content

**Comment by shhossain** [comment]
@all-contributors add @manavmittal05 for content

**Pull request merged**
