### PR TITLE
Added for Binary to Decimal and Hexadecimal Conversion

### PR DESCRIPTION
**Pull request by ShivanshDengla**
## Proposed changes
Added for Binary to Decimal and Hexadecimal Conversion

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [ ] Proofreading (fix spelling, grammar, punctuation, accuracy) [More about Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ ] New Files/Folder (adding folder without removing existing one)
- [x] Add/Remove Files (adding/removing existing files/folder)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._

- [ ] Tested any code against its gcc/clang or the official binaries and it passes locally with my changes
- [ ] I have added the necessary explanation
- [x] I have added the necessary links in the working section
- [ ] Added external links

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### Reviewers: 

This will be filled by the people who review this particular Pull Request.

### CODE REVIEW

**Comment by ShivanshDengla** [comment]
Hey,
Added changes for binary to decimal and hexadecimal conversion. Do let me know if theres any mistake.
Thanks you.

**Review by shhossain — APPROVED** [review]
Merging.

**Comment by ShivanshDengla** [comment]
> 

Hey,
can you give hacktober accepted tag for it to be counted in hacktober?
Thanks

**Comment by shhossain** [comment]
@ShivanshDengla you need minimum 100 unique additions to get that label.

**Pull request merged**
