### PR TITLE
HashTable readme

### PR DESCRIPTION
**Pull request by Sangjukta3011**
## Proposed changes

Added content for hash table.

## Types of changes

What types of changes does your code introduce to this project?
_Put an `x` in the boxes that apply_

- [x] Proofreading (fix spelling, grammar, punctuation, accuracy) [More about Proofreading](https://www.scribbr.com/language-rules/what-is-proofreading/)
- [ ] New Files/Folder (adding folder without removing existing one)
- [ ] Add/Remove Files (adding/removing existing files/folder)

## Checklist

_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. Don't hesitate to ask if you're unsure about any of them. We're here to help! This is simply a reminder of what we will look for before merging your code._

- [] Tested any code against its gcc/clang or the official binaries and it passes locally with my changes
- [x] I have added the necessary explanation
- [ ] I have added the necessary links in the working section
- [ ] Added external links

## Further comments

If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...

### Reviewers: 

This will be filled by the people who review this particular Pull Request.

### CODE REVIEW

**Review by shhossain — CHANGES_REQUESTED** [review]
It shows you've removed content from the hash table.

**Comment by Sangjukta3011** [comment]
I have copied and pasted the folder again and added changes.

**Comment by Sangjukta3011** [comment]
wouldn't that work?

**Comment by shhossain** [comment]
@Sangjukta3011 it looks like you've mistakenly removed the content in hash table readme.

**Comment by Sangjukta3011** [comment]
ooh ok i will change it

**Comment by Sangjukta3011** [comment]
my additions on the content are not getting displayed and it's also showing i have removed the content. what should I do

**Comment by Sangjukta3011** [comment]
image
looks like this

**Comment by shhossain** [comment]
@Sangjukta3011 
image
image

You are sending the wrong branch in your PR.

**Comment by Sangjukta3011** [comment]
ooh got it now

**Pull request closed without merging**
